### ISSUE TITLE
Implement Indices for Eod Endpoint

### ISSUE THREAD

**Issue by reubenwong97** [reubenwong97/marketstack-rs#15]
Description:
> The API is also capable of delivering end-of-day for 750+ of the world's major indices, including the S&P 500 Index, the Dow Jones Industrial Average Index as well as the NASDAQ Composite Index. Index data is available both on a "latest" basis as well as historically.

> To list or access index data, simply pass `INDX` as your stock exchange MIC identification, as seen in the examples below. The example API request below illustrates how to obtain end-of-day data for the `DJI` market index.

## Tasks

- [x] Obtain all available market indices by passing INDX as the exchange MIC identification.
- [ ] Obtain meta information for a specific market index.
- [ ] Obtain end-of-day data for a specific market index.

## API Response:
```json
{
    "pagination": {
        "limit": 1,
        "offset": 0,
        "count": 1,
        "total": 7561
    },
    "data": [
        {
            "date": "2020-08-21T00:00:00+0000",
            "symbol": "DJI.INDX",
            "exchange": "INDX",
            "open": 27758.1309,
            "high": 27959.4805,
            "low": 27686.7793,
            "close": 27930.3301,
            "volume": 374339179,
            "adj_high": null,
            "adj_low": null,
            "adj_close": 27930.3301,
            "adj_open": null,
            "adj_volume": null
        }
    ]
}
```

## Market Indices in Other API Endpoints:
Object | Description
-- | --
/exchanges/INDX/tickers | Obtain all available market indices by passing INDX as the exchange MIC identification.
/tickers/[symbol].INDX | Obtain meta information for a specific market index.
/tickers/[symbol].INDX/eod | Obtain end-of-day data for a specific market index.

**Comment by reubenwong97** [comment]
Without access to the endpoint, I cannot realistically implement it since I don't know what the return type is like. This will be on-hold until further notice.
