### ISSUE TITLE
TODO: Refactor Eod Endpoint

### ISSUE THREAD

**Issue by reubenwong97** [reubenwong97/marketstack-rs#6]
Currently, `eod`, `eod/latest` and `eod/[date]` are implemented as 3 separate structs and endpoints. However, I realised that this need not be the case and I should in fact simply add more fields to the `Eod` struct. When implementing the `endpoint` method for the `Endpoint` trait, I then form the endpoint programmatically based on what was built with the `EodBuilder`.

### Tasks
- [x] Refactor `Eod` to have `latest` field as a bool flag and `date` as an `Option<NaiveDate>` that can be specified.
- [x] Bake `EodLatest` into `Eod`
- [x] Base `EodDate` into `Eod`
- [x] Programmatically set `endpoint` based on built values from `EodBuilder`
