### ISSUE TITLE
Implement Tickers Endpoint

### ISSUE THREAD

**Issue by reubenwong97** [reubenwong97/marketstack-rs#9]
Description:
> Using the API's `tickers` endpoint you will be able to look up information about one or multiple stock ticker symbols as well as obtain end-of-day, real-time and intraday market data for single tickers. You will be able to find and try out an example API request below.

## Tasks
- [x] Implement base `tickers` endpoint
- [x] Implement `tickers/eod*` endpoints
- [x] Implement `tickers/splits*` endpoints
- [x] Implement `tickers/dividends*` endpoints

## Endpoint Features:
Object | Description
-- | --
/tickers/[symbol] | Obtain information about a specific ticker symbol by attach it to your API request URL, e.g. /tickers/AAPL.
/tickers/[symbol]/eod | Obtain end-of-day data for a specific stock ticker by attaching /eod to your URL, e.g. /tickers/AAPL/eod. This route supports parameters of the End-of-day Data endpoint.
/tickers/[symbol]/splits | Obtain end-of-day data for a specific stock ticker by attaching /splits to your URL, e.g. /tickers/AAPL/splits. This route supports parameters like date period date_from and date_to and also you can sort the results DESC or ASC.
/tickers/[symbol]/dividends | Obtain end-of-day data for a specific stock ticker by attaching /dividends to your URL, e.g. /tickers/AAPL/dividends. This route supports parameters like date period date_from and date_to and also you can sort the results DESC or ASC.
/tickers/[symbol]/intraday | Obtain real-time & intraday data for a specific stock ticker by attaching /intraday to your URL, e.g. /tickers/AAPL/intraday. This route supports parameters of the Intraday Data endpoint.
/tickers/[symbol]/eod/[date] | Specify a date in YYYY-MM-DD format. You can also specify an exact time in ISO-8601 date format, e.g. 2020-05-21T00:00:00+0000. Example: /eod/2020-01-01 or /intraday/2020-01-01
/tickers/[symbol]/eod/latest | Obtain the latest end-of-day data for a given stock symbol. Example: /tickers/AAPL/eod/latest
/tickers/[symbol]/intraday/latest | Obtain the latest intraday data for a given stock symbol. Example: /tickers/AAPL/intraday/latest

## HTTP GET Request Parameters:
Object | Description
-- | --
access_key | [Required] Specify your API access key, available in your account dashboard.
exchange | [Optional] To filter your results  based on a specific stock exchange, use this parameter to specify the  MIC identification of a stock exchange. Example: XNAS
search | [Optional] Use this parameter to search stock tickers by name or ticker symbol.
limit | [Optional] Specify a pagination limit (number of results per page) for your API request. Default limit value is 100, maximum allowed limit value is 1000.
offset | [Optional] Specify a pagination offset value for your API request. Example: An offset value of 100 combined with a limit value of 10 would show results 100-110. Default value is 0, starting with the first available result.

## API Response:
```json
{
    "pagination": {
        "limit": 100,
        "offset": 0,
        "count": 100,
        "total": 136785
    },
    "data": [
        {
            "name": "MICROSOFT CORP",
            "symbol": "MSFT",
            "stock_exchange": {
                "name": "NASDAQ Stock Exchange",
                "acronym": "NASDAQ",
                "mic": "XNAS",
                "country": "USA",
                "country_code": "US",
                "city": "New York",
                "website": "www.nasdaq.com",
                "timezone": {
                    "timezone": "America/New_York",
                    "abbr": "EST",
                    "abbr_dst": "EDT"
                }
            }
        },
        [...]
    ]
}
```

## API Response Objects
Response Object | Description
-- | --
pagination > limit | Returns your pagination limit value.
pagination > offset | Returns your pagination offset value.
pagination > count | Returns the results count on the current page.
pagination > total | Returns the total count of results available.
name | Returns the name of the given stock ticker.
symbol | Returns the symbol of the given stock ticker.
stock_exchange > name | Returns the name of the stock exchange associated with the given stock ticker.
stock_exchange > acronym | Returns the acronym of the stock exchange associated with the given stock ticker.
stock_exchange > mic | Returns the MIC identification of the stock exchange associated with the given stock ticker.
stock_exchange > country | Returns the country of the stock exchange associated with the given stock ticker.
stock_exchange > country_code | Returns the 3-letter country code of the stock exchange associated with the given stock ticker.
stock_exchange > city | Returns the city of the stock exchange associated with the given stock ticker.
stock_exchange > website | Returns the website URL of the stock exchange associated with the given stock ticker.
timezone > timezone | Returns the timezone name of the stock exchange associated with the given stock ticker.
timezone > abbr | Returns the timezone abbreviation of the stock exchange associated with the given stock ticker.
timezone > abbr_dst | Returns the Summer time timezone abbreviation of the stock exchange associated with the given stock ticker.
